#!/bin/bash
clear
choice=""
while [ ! "$choice" = "Q" ] && [ ! "$choice" = "q" ]; do
	echo "L)ist all process"
	echo "O)wned by you processes"
	echo "T)ree of all processes"
	echo "C)ount processes"
	read -r -p "Make a selection please: " choice

	if [ "$choice" = "" ]; then
		echo "You did not make a selection"
		echo 
		continue
	fi

	if [ "$choice" = "L" ] || [ "$choice" = "l" ]; then
		ps aux
		echo
		continue
	fi

	if [ "$choice" = "O" ] || [ "$choice" = "o" ]; then
		ps
		echo
		continue
	fi

	if [ "$choice" = "T" ] || [ "$choice" = "t" ]; then
		ps axjf
		echo
		continue
	fi

	if [ "$choice" = "C" ] || [ "$choice" = "c" ]; then
		count=$(ps aux | grep -c "")
		echo "Number of users: $count"
		echo
		continue
	fi

	if [ "$choice" = "Q" ] || [ "$choice" = "q" ]; then
		echo "Bye"
		echo
		continue
	fi
done
